[package]
name = "transgender"
version = "0.1.0"
edition = "2021"

[dependencies.crossterm]
version = "0.26"
features = ["event-stream"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
